export const Data = [
  {
    id: 1,
    title: 'Portfólio',
    image: '/img/portfolio/portfolio.png',
    github: 'https://github.com/dalcastagned/portfolio',
  },
  {
    id: 2,
    title: 'Solar Energy Refactor (Frontend)',
    image: '/img/portfolio/solar-energy-refactor-frontend.png',
    github: 'https://github.com/dalcastagned/solar-energy-frontend',
  },
  {
    id: 3,
    title: 'Solar Energy (Backend)',
    image: '/img/portfolio/solar-energyr-backend.png',
    github: 'https://github.com/dalcastagned/solar-energy-backend',
  },
  {
    id: 4,
    title: 'Shopping List',
    image: '/img/portfolio/shopping-list.png',
    github: 'https://github.com/dalcastagned/shopping-list-app',
    demo: 'https://listaparacompras.vercel.app/',
  },
  {
    id: 5,
    title: 'Breaking Bad',
    image: '/img/portfolio/breaking-bad.png',
    github: 'https://github.com/dalcastagned/breaking-bad',
    demo: 'https://breaking-bad-gilt.vercel.app/',
  },
  {
    id: 6,
    title: 'Informações e Noticias Sobre MMOs',
    image: '/img/portfolio/mmo.png',
    github: 'https://github.com/dalcastagned/mmo-react-complete-site',
    demo: 'https://mmo-react-complete-site.vercel.app/',
  },
  {
    id: 7,
    title: 'Solar Energy (com JSON-SERVER)',
    image: '/img/portfolio/solar-energy.png',
    github: 'https://github.com/dalcastagned/solar-energy-json-server',
  },
  {
    id: 8,
    title: 'Eccomerce Yu-Gi-Oh',
    image: '/img/portfolio/yu-gi-oh.png',
    github: 'https://github.com/dalcastagned/ecommerce-yugioh',
    demo: 'https://ecommerce-yugioh.vercel.app/',
  },
  {
    id: 9,
    title: 'To-Do List',
    image: '/img/portfolio/to-do-list.png',
    github: 'https://github.com/dalcastagned/to-do-list-locastorage',
    demo: 'https://to-do-list-locastorage.vercel.app/',
  },
  {
    id: 10,
    title: 'Thabatta Alegria Website',
    image: '/img/portfolio/thabatta.png',
    github: 'https://github.com/dalcastagned/thabatta-alegria-website',
    demo: 'https://thabatta-alegria-website.vercel.app/',
  },
  {
    id: 11,
    title: 'Landing Page Daniel Dalcastagne',
    image: '/img/portfolio/daniel.png',
    github: 'https://github.com/dalcastagned/landing-page-daniel-dalcastagne',
    demo: 'https://landing-page-daniel-dalcastagne.vercel.app/',
  },
];
